- name: Install Required Packages for App
  when: ansible_hostname == "app"
  yum:
    name:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed


- name: Enable PHP 7.3 Remi repository
  when: ansible_hostname == "app"
  command: yum-config-manager --enable remi-php73

- name: Update PHP
  when: ansible_hostname == "app" 
  yum:
    name:
      - php-mysql
      - php 
      - php-common 
      - php-opcache 
      - php-mcrypt 
      - php-cli
      - php-gd 
      - php-curl
      - php-mysqlnd
      - php-xml
      - php-mbstring
      - mysql
    state: latest  