- name: MariaDB installation
  when: ansible_hostname == "mysql"
  yum:
    name:
      - mariadb
      - mariadb-server
      - MySQL-python
  register: db_installation  

- name: Start and Enable MariaDB
  when: ansible_hostname == "mysql"
  systemd:
    name: mariadb
    state: started
    enabled: yes