- name: Set root password
  when: 
    - db_installation.changed
    - ansible_hostname == "mysql" 
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present


- name: Remove Annonymous User
  when: 
    - db_installation.changed
    - ansible_hostname == "mysql" 
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: "{{ mysql_root_password }}"
    name: ''
    host_all: yes
    state: absent
    
- name: Remove Test Database
  when: ansible_hostname == "mysql" 
  mysql_db:
    login_host: 'localhost'
    login_user: 'root'
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent


